//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayRollWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loans()
        {
            this.PayRollDetail = new HashSet<PayRollDetail>();
        }
    
        public int Id { get; set; }
        public int Employee { get; set; }
        public System.DateTime StartDate { get; set; }
        public decimal Amount { get; set; }
        public decimal Balance { get; set; }
    
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayRollDetail> PayRollDetail { get; set; }
    }
}
