//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayRollWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayRollDetail
    {
        public int Id { get; set; }
        public Nullable<decimal> ExtraDay { get; set; }
        public Nullable<decimal> Advancement { get; set; }
        public Nullable<int> Loan { get; set; }
        public Nullable<decimal> Incentive { get; set; }
        public Nullable<decimal> Holidays { get; set; }
        public Nullable<decimal> Bonus { get; set; }
        public System.DateTime Date { get; set; }
        public int PayRoll { get; set; }
    
        public virtual Loans Loans { get; set; }
        public virtual PayRoll PayRoll1 { get; set; }
    }
}
